###=========================================================
### Birdiary REST Client Requests Docs & Testing
###=========================================================

############################################################
############################################################
############################################################

### USERS
###=========================================================

# GET /users
# Get a single user.

GET {{baseUrl}}/users
Authorization: Bearer {{jwt}}

###=========================================================

# PATCH /users
# Update a single user.

PATCH {{baseUrl}}/users
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "address": "Alameda, CA 94501, USA",
  "bio": "Lorem ipsum...",
  "name": "Test User",
  "zipcode": "94501"
}

###=========================================================

# DELETE /users
# Delete a single user.

DELETE {{baseUrl}}/users
Authorization: Bearer {{jwt}}

###=========================================================

# GET /users/stats
# Get a single user's sighting statistics.

GET {{baseUrl}}/users/stats
Authorization: Bearer {{jwt}}


###=========================================================

# POST /users/signup
# Create a new user.

POST {{baseUrl}}/users/signup
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###=========================================================

# POST /users/signin
# Authenticate user's credentials.

POST {{baseUrl}}/users/signin
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###=========================================================

# PATCH /users/favoritebird
# Update user's favorite bird.

PATCH {{baseUrl}}/users/favoritebird
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "favoriteBirdId": 112
}

###=========================================================

# PATCH /users/password
# Update user's password.

PATCH {{baseUrl}}/users/password
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "currentPassword": "{{password}}",
  "newPassword": "{{updatePassword}}"
}

###=========================================================

# POST /users/transferstorage
# Add sightings data from user's browser to db.

POST {{baseUrl}}/users/transferstorage
Authorization: Bearer {{jwt}}

# Note: Need to update with request body

############################################################
############################################################
############################################################

### BIRDS
###=========================================================

# GET /birds
# Get list of birds. Attach token to include sightings count.

# Query Parameters:
#   page (number, required) - required for pagination
#   search (string, optional) - filter by search string (overrides startsWith)
#   startsWith (char, optional) - filter by first letter of common name

GET {{baseUrl}}/birds?page=1&search=jay
Authorization: Bearer {{jwt}}

###=========================================================

# GET /birds/:id
# Get a single bird with image.

GET {{baseUrl}}/birds/112

###=========================================================

# GET /birds/:id/sightings
# Get user's sightings by single bird.

# Query Parameters:
#   page (number, required) - required for pagination
#   sortBy (string, required) - 'dateAsc', 'dateDesc'

GET {{baseUrl}}/birds/112/sightings?page=1&sortBy=dateDesc
Authorization: Bearer {{jwt}}

############################################################
############################################################
############################################################

### Bird of the Day
###=========================================================

# GET /birdoftheday
# Get bird of the day.

GET {{baseUrl}}/birdoftheday

############################################################
############################################################
############################################################

### LOCATIONS
###=========================================================

# GET /locations
# Get user's locations.

# Query Parameters:
#   page (number, required) - required for pagination
#   sortBy (string, required) - 'alphaAsc', 'alphaDesc', 'count'

GET {{baseUrl}}/locations?page=1&sortBy=alphaAsc
Authorization: Bearer {{jwt}}

###=========================================================

# GET /locations/:id
# Get a single location.

GET {{baseUrl}}/locations/1
Authorization: Bearer {{jwt}}

###=========================================================

# PUT /locations/:id
# Upserts a single location.

PUT {{baseUrl}}/locations/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

# Note: need to add request body

###=========================================================

# DELETE /locations/:id
# Delete a single location and remove from related sightings.

DELETE {{baseUrl}}/locations/1
Authorization: Bearer {{jwt}}

###=========================================================

# GET /locations/:id/sightings
# Get user's sightings by single location.

# Query Parameters:
#   page (number, required) - required for pagination
#   sortBy (string, required) - 'alphaAsc', 'alphaDesc', 'dateAsc', 'dateDesc'

GET {{baseUrl}}/locations/1/sightings?page=1&sortBy=alphaAsc
Authorization: Bearer {{jwt}}

############################################################
############################################################
############################################################

### SIGHTINGS
###=========================================================

# POST /sightings
# Create a new sighting.

POST {{baseUrl}}/sightings
Authorization: Bearer {{jwt}}
Content-Type: application/json

# Need to add request body

###=========================================================

# GET /sightings
# Get user's sightings.

# Query Parameters:
#   page (number, required) - required for pagination
#   sortBy (string, required) - 'alphaAsc', 'alphaDesc', 'count', 'dateAsc', 'dateDesc'

# Need to add additional query parameters

GET {{baseUrl}}/sightings?page=1&sortBy=dateDesc
Authorization: Bearer {{jwt}}

###=========================================================

# GET /sightings/:id
# Get a single sighting.

GET {{baseUrl}}/sightings/1
Authorization: Bearer {{jwt}}

###=========================================================

# PATCH /sightings/:id
# Update a single sighting.

PATCH {{baseUrl}}/sightings/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

# Need to add request body

###=========================================================

# DELETE /sightings/:id
# Delete a single sighting.

DELETE {{baseUrl}}/sightings/1
Authorization: Bearer {{jwt}}