const birdNames: string[] = [
  "Abert's Towhee",
  'Acadian Flycatcher',
  'Acorn Woodpecker',
  'African Silverbill',
  'Akekee',
  'Akiapolaau',
  'Akikiki',
  'Akohekohe',
  'Alder Flycatcher',
  'Aleutian Tern',
  "Allen's Hummingbird",
  'Altamira Oriole',
  'American Avocet',
  'American Barn Owl',
  'American Bittern',
  'American Black Duck',
  'American Coot',
  'American Crow',
  'American Dipper',
  'American Flamingo',
  'American Golden-Plover',
  'American Goldfinch',
  'American Goshawk',
  'American Kestrel',
  'American Oystercatcher',
  'American Pipit',
  'American Redstart',
  'American Robin',
  'American Three-toed Woodpecker',
  'American Tree Sparrow',
  'American White Pelican',
  'American Wigeon',
  'American Woodcock',
  'Ancient Murrelet',
  'Anhinga',
  'Anianiau',
  "Anna's Hummingbird",
  'Antillean Nighthawk',
  'Apapane',
  'Aplomado Falcon',
  'Arctic Loon',
  'Arctic Tern',
  'Arctic Warbler',
  'Arizona Woodpecker',
  'Ash-throated Flycatcher',
  'Ashy Storm-Petrel',
  'Atlantic Puffin',
  "Audubon's Oriole",
  "Bachman's Sparrow",
  "Baird's Sandpiper",
  "Baird's Sparrow",
  'Bald Eagle',
  'Baltimore Oriole',
  'Band-rumped Storm-Petrel',
  'Band-tailed Pigeon',
  'Bank Swallow',
  'Bar-tailed Godwit',
  'Barn Swallow',
  'Barnacle Goose',
  'Barred Owl',
  "Barrow's Goldeneye",
  'Bay-breasted Warbler',
  "Bell's Sparrow",
  "Bell's Vireo",
  'Belted Kingfisher',
  "Bendire's Thrasher",
  'Bermuda Petrel',
  'Berylline Hummingbird',
  "Bewick's Wren",
  "Bicknell's Thrush",
  'Black Francolin',
  'Black Guillemot',
  'Black Noddy',
  'Black Oystercatcher',
  'Black Phoebe',
  'Black Rail',
  'Black Rosy-Finch',
  'Black Scoter',
  'Black Skimmer',
  'Black Storm-Petrel',
  'Black Swift',
  'Black Tern',
  'Black Turnstone',
  'Black Vulture',
  'Black-and-white Warbler',
  'Black-backed Woodpecker',
  'Black-bellied Plover',
  'Black-bellied Whistling-Duck',
  'Black-billed Cuckoo',
  'Black-billed Magpie',
  'Black-capped Chickadee',
  'Black-capped Gnatcatcher',
  'Black-capped Petrel',
  'Black-capped Vireo',
  'Black-chinned Hummingbird',
  'Black-chinned Sparrow',
  'Black-crested Titmouse',
  'Black-crowned Night Heron',
  'Black-footed Albatross',
  'Black-headed Grosbeak',
  'Black-headed Gull',
  'Black-legged Kittiwake',
  'Black-necked Stilt',
  'Black-tailed Gnatcatcher',
  'Black-tailed Godwit',
  'Black-throated Blue Warbler',
  'Black-throated Gray Warbler',
  'Black-throated Green Warbler',
  'Black-throated Sparrow',
  'Black-vented Shearwater',
  'Black-whiskered Vireo',
  'Black-winged Petrel',
  'Blackburnian Warbler',
  'Blackpoll Warbler',
  'Blue Grosbeak',
  'Blue Jay',
  'Blue-gray Gnatcatcher',
  'Blue-gray Noddy',
  'Blue-headed Vireo',
  'Blue-throated Mountain-gem',
  'Blue-winged Teal',
  'Blue-winged Warbler',
  'Bluethroat',
  'Boat-tailed Grackle',
  'Bobolink',
  'Bohemian Waxwing',
  "Bonaparte's Gull",
  'Bonin Petrel',
  'Boreal Chickadee',
  'Boreal Owl',
  "Botteri's Sparrow",
  'Brambling',
  "Brandt's Cormorant",
  'Brant',
  "Brewer's Blackbird",
  "Brewer's Sparrow",
  'Bridled Tern',
  'Bridled Titmouse',
  'Bristle-thighed Curlew',
  'Broad-billed Hummingbird',
  'Broad-tailed Hummingbird',
  'Broad-winged Hawk',
  'Bronzed Cowbird',
  'Brown Booby',
  'Brown Creeper',
  'Brown Noddy',
  'Brown Pelican',
  'Brown Thrasher',
  'Brown-capped Rosy-Finch',
  'Brown-crested Flycatcher',
  'Brown-headed Cowbird',
  'Brown-headed Nuthatch',
  'Buff-bellied Hummingbird',
  'Buff-breasted Flycatcher',
  'Buff-breasted Sandpiper',
  'Buff-collared Nightjar',
  'Bufflehead',
  "Buller's Shearwater",
  "Bullock's Oriole",
  "Bulwer's Petrel",
  'Burrowing Owl',
  'Bushtit',
  'Cackling Goose',
  'Cactus Wren',
  'California Condor',
  'California Gnatcatcher',
  'California Gull',
  'California Quail',
  'California Scrub-Jay',
  'California Thrasher',
  'California Towhee',
  'Calliope Hummingbird',
  'Canada Goose',
  'Canada Jay',
  'Canada Warbler',
  'Canvasback',
  'Canyon Towhee',
  'Canyon Wren',
  'Cape May Warbler',
  'Carolina Chickadee',
  'Carolina Wren',
  'Caspian Tern',
  'Cassia Crossbill',
  "Cassin's Auklet",
  "Cassin's Finch",
  "Cassin's Kingbird",
  "Cassin's Sparrow",
  "Cassin's Vireo",
  'Cave Swallow',
  'Cedar Waxwing',
  'Cerulean Warbler',
  'Chestnut Munia',
  'Chestnut-backed Chickadee',
  'Chestnut-bellied Sandgrouse',
  'Chestnut-collared Longspur',
  'Chestnut-sided Warbler',
  'Chihuahuan Meadowlark',
  'Chihuahuan Raven',
  'Chimney Swift',
  'Chinese Hwamei (Hwamei)',
  'Chipping Sparrow',
  'Christmas Shearwater',
  "Chuck-will's-widow",
  'Chukar',
  'Cinnamon Teal',
  'Clapper Rail',
  "Clark's Grebe",
  "Clark's Nutcracker",
  'Clay-colored Sparrow',
  'Clay-colored Thrush',
  'Cliff Swallow',
  'Cocos Booby',
  'Colima Warbler',
  'Common Black Hawk',
  'Common Cuckoo',
  'Common Eider',
  'Common Gallinule',
  'Common Goldeneye',
  'Common Grackle',
  'Common Greenshank',
  'Common Ground Dove',
  'Common Gull',
  'Common Loon',
  'Common Merganser',
  'Common Murre',
  'Common Myna',
  'Common Nighthawk',
  'Common Pauraque',
  'Common Pochard',
  'Common Poorwill',
  'Common Raven',
  'Common Redpoll (Redpoll)',
  'Common Ringed Plover',
  'Common Sandpiper',
  'Common Snipe',
  'Common Tern',
  'Common Waxbill',
  'Common Yellowthroat',
  'Connecticut Warbler',
  "Cook's Petrel",
  "Cooper's Hawk",
  "Cory's Shearwater",
  "Costa's Hummingbird",
  "Couch's Kingbird",
  "Craveri's Murrelet",
  'Crested Auklet',
  'Crested Caracara',
  'Crissal Thrasher',
  'Curlew Sandpiper',
  'Curve-billed Thrasher',
  'Dark-eyed Junco',
  'Dickcissel',
  'Double-crested Cormorant',
  'Dovekie',
  'Downy Woodpecker',
  'Dunlin',
  'Dusky Flycatcher',
  'Dusky Grouse',
  'Dusky-capped Flycatcher',
  'Eared Grebe',
  'Eastern Bluebird',
  'Eastern Kingbird',
  'Eastern Meadowlark',
  'Eastern Phoebe',
  'Eastern Screech-Owl',
  'Eastern Towhee',
  'Eastern Whip-poor-will',
  'Eastern Wood-Pewee',
  'Eastern Yellow Wagtail',
  'Egyptian Goose',
  'Elegant Tern',
  'Elegant Trogon',
  'Elf Owl',
  'Emperor Goose',
  "Erckel's Spurfowl (Francolin)",
  'Eurasian Collared-Dove',
  'Eurasian Skylark',
  'Eurasian Tree Sparrow',
  'Eurasian Wigeon',
  'European Goldfinch',
  'European Starling',
  'Evening Grosbeak',
  'Eyebrowed Thrush',
  "Fea's Petrel",
  'Ferruginous Hawk',
  'Ferruginous Pygmy-Owl',
  'Field Sparrow',
  'Fish Crow',
  'Five-striped Sparrow',
  'Flame-colored Tanager',
  'Flammulated Owl',
  'Flesh-footed Shearwater',
  'Florida Scrub-Jay',
  'Fork-tailed Flycatcher',
  'Fork-tailed Storm-Petrel',
  "Forster's Tern",
  'Fox Sparrow',
  "Franklin's Gull",
  'Fulvous Whistling-Duck',
  'Gadwall',
  "Gambel's Quail",
  'Gila Woodpecker',
  'Gilded Flicker',
  'Glaucous Gull',
  'Glaucous-winged Gull',
  'Glossy Ibis',
  'Golden Eagle',
  'Golden-cheeked Warbler',
  'Golden-crowned Kinglet',
  'Golden-crowned Sparrow',
  'Golden-fronted Woodpecker',
  'Golden-winged Warbler',
  "Grace's Warbler",
  'Grasshopper Sparrow',
  'Gray Catbird',
  'Gray Flycatcher',
  'Gray Francolin',
  'Gray Hawk',
  'Gray Kingbird',
  'Gray Partridge',
  'Gray Vireo',
  'Gray-backed Tern',
  'Gray-cheeked Thrush',
  'Gray-crowned Rosy-Finch',
  'Gray-headed (Purple) Swamphen',
  'Gray-headed Chickadee',
  'Gray-tailed Tattler',
  'Great Black-backed Gull',
  'Great Blue Heron',
  'Great Cormorant',
  'Great Crested Flycatcher',
  'Great Egret',
  'Great Frigatebird',
  'Great Gray Owl',
  'Great Horned Owl',
  'Great Kiskadee',
  'Great Shearwater',
  'Great Skua',
  'Great-tailed Grackle',
  'Greater Necklaced Laughingthrush',
  'Greater Pewee',
  'Greater Prairie-Chicken',
  'Greater Roadrunner',
  'Greater Sage-Grouse',
  'Greater Scaup',
  'Greater White-fronted Goose',
  'Greater Yellowlegs',
  'Green Heron',
  'Green Jay',
  'Green Kingfisher',
  'Green Parakeet',
  'Green-tailed Towhee',
  'Green-winged Teal',
  'Groove-billed Ani',
  'Guadalupe Murrelet',
  'Gull-billed Tern',
  'Gunnison Sage-Grouse',
  'Gyrfalcon',
  'Hairy Woodpecker',
  "Hammond's Flycatcher",
  'Harlequin Duck',
  "Harris's Hawk",
  "Harris's Sparrow",
  'Hawaii Akepa',
  'Hawaii Amakihi',
  'Hawaii Creeper',
  'Hawaii Elepaio',
  'Hawaiian Coot',
  'Hawaiian Duck',
  'Hawaiian Goose',
  'Hawaiian Hawk',
  'Hawaiian Petrel',
  "Heermann's Gull",
  "Henslow's Sparrow",
  'Hepatic Tanager',
  'Hermit Thrush',
  'Hermit Warbler',
  'Herring Gull',
  'Himalayan Snowcock',
  'Hooded Merganser',
  'Hooded Oriole',
  'Hooded Warbler',
  'Hook-billed Kite',
  'Horned Grebe',
  'Horned Lark',
  'Horned Puffin',
  'House Finch',
  'House Sparrow',
  'Hudsonian Godwit',
  "Hutton's Vireo",
  'Iceland Gull',
  'Iiwi',
  'Inca Dove',
  'Indian Peafowl',
  'Indigo Bunting',
  'Island Canary',
  'Island Scrub-Jay',
  'Ivory Gull',
  'Japanese Bush Warbler',
  'Java Sparrow',
  'Juan Fernandez Petrel',
  'Juniper Titmouse',
  'Kalij Pheasant',
  'Kauai Amakihi',
  'Kauai Elepaio',
  'Kentucky Warbler',
  'Killdeer',
  'King Eider',
  'King Rail',
  "Kirtland's Warbler",
  "Kittlitz's Murrelet",
  "La Sagra's Flycatcher",
  'Ladder-backed Woodpecker',
  'Lapland Longspur',
  'Lark Bunting',
  'Lark Sparrow',
  'Laughing Gull',
  'Lavender Waxbill ',
  "Lawrence's Goldfinch",
  'Laysan Albatross',
  'Laysan Duck',
  'Laysan Finch',
  'Lazuli Bunting',
  "Leach's Storm-Petrel",
  'Least Auklet',
  'Least Bittern',
  'Least Flycatcher',
  'Least Grebe',
  'Least Sandpiper',
  'Least Storm-Petrel',
  'Least Tern',
  "LeConte's Sparrow",
  "LeConte's Thrasher",
  'Lesser Black-backed Gull',
  'Lesser Goldfinch',
  'Lesser Nighthawk',
  'Lesser Prairie-Chicken',
  'Lesser Scaup',
  'Lesser Yellowlegs',
  "Lewis's Woodpecker",
  'Lilac-crowned Parrot',
  'Limpkin',
  "Lincoln's Sparrow",
  'Little Blue Heron',
  'Little Gull',
  'Little Stint',
  'Loggerhead Shrike',
  'Long-billed Curlew',
  'Long-billed Dowitcher',
  'Long-billed Thrasher',
  'Long-eared Owl',
  'Long-tailed Duck',
  'Long-tailed Jaeger',
  'Long-toed Stint',
  'Louisiana Waterthrush',
  'Lucifer Hummingbird',
  "Lucy's Warbler",
  "MacGillivray's Warbler",
  'Magnificent Frigatebird',
  'Magnolia Warbler',
  'Mallard',
  'Mangrove Cuckoo',
  'Manx Shearwater',
  'Marbled Godwit',
  'Marbled Murrelet',
  'Mariana Swiftlet',
  'Marsh Wren',
  'Masked Booby',
  'Masked Duck',
  'Maui Alauahio',
  'Maui Parrotbill',
  "McKay's Bunting",
  'Merlin',
  'Mexican Chickadee',
  'Mexican Duck',
  'Mexican Jay',
  'Mexican Violetear',
  'Mexican Whip-poor-will',
  'Millerbird',
  'Mississippi Kite',
  'Mitred Parakeet',
  'Monk Parakeet',
  'Montezuma Quail',
  "Morelet's Seedeater",
  'Mottled Duck',
  'Mottled Petrel',
  'Mountain Bluebird',
  'Mountain Chickadee',
  'Mountain Plover',
  'Mountain Quail',
  'Mourning Dove',
  'Mourning Warbler',
  "Murphy's Petrel",
  'Muscovy Duck',
  'Mute Swan',
  'Nanday Parakeet',
  'Nashville Warbler',
  'Nazca Booby',
  "Nelson's Sparrow",
  'Neotropic Cormorant',
  "Newell's Shearwater",
  'Nihoa Finch',
  'Northern Beardless-Tyrannulet',
  'Northern Bobwhite',
  'Northern Cardinal',
  'Northern Flicker',
  'Northern Fulmar',
  'Northern Gannet',
  'Northern Harrier',
  'Northern Hawk Owl',
  'Northern House Wren',
  'Northern Mockingbird',
  'Northern Parula',
  'Northern Pintail',
  'Northern Pygmy-Owl',
  'Northern Rough-winged Swallow',
  'Northern Saw-whet Owl',
  'Northern Shoveler',
  'Northern Shrike',
  'Northern Waterthrush',
  'Northern Wheatear',
  "Nuttall's Woodpecker",
  'Oahu Amakihi',
  'Oahu Elepaio',
  'Oak Titmouse',
  'Olive Sparrow',
  'Olive Warbler',
  'Olive-backed Pipit',
  'Olive-sided Flycatcher',
  'Omao',
  'Orange-crowned Warbler',
  'Orchard Oriole',
  'Osprey',
  'Ovenbird',
  'Pacific Golden-Plover',
  'Pacific Loon',
  'Pacific Wren',
  'Painted Bunting',
  'Painted Redstart',
  'Palila',
  'Palm Warbler',
  'Parakeet Auklet',
  'Parasitic Jaeger',
  'Pectoral Sandpiper',
  'Pelagic Cormorant',
  'Peregrine Falcon',
  'Phainopepla',
  'Philadelphia Vireo',
  'Pied-billed Grebe',
  'Pigeon Guillemot',
  'Pileated Woodpecker',
  'Pine Grosbeak',
  'Pine Siskin',
  'Pine Warbler',
  'Pink-footed Goose',
  'Pink-footed Shearwater',
  'Pinyon Jay',
  'Piping Plover',
  'Plain Chachalaca',
  'Plumbeous Vireo',
  'Pomarine Jaeger',
  'Prairie Falcon',
  'Prairie Warbler',
  'Prothonotary Warbler',
  'Puaiohi',
  'Purple Finch',
  'Purple Gallinule',
  'Purple Martin',
  'Purple Sandpiper',
  'Pygmy Nuthatch',
  'Pyrrhuloxia',
  'Razorbill',
  'Red Avadavat',
  'Red Crossbill',
  'Red Junglefowl',
  'Red Knot',
  'Red Phalarope',
  'Red-bellied Woodpecker',
  'Red-billed Leiothrix',
  'Red-billed Pigeon',
  'Red-billed Tropicbird',
  'Red-breasted Merganser',
  'Red-breasted Nuthatch',
  'Red-breasted Sapsucker',
  'Red-cockaded Woodpecker',
  'Red-crested Cardinal',
  'Red-crowned Parrot',
  'Red-eyed Vireo',
  'Red-faced Cormorant',
  'Red-faced Warbler',
  'Red-footed Booby',
  'Red-headed Woodpecker',
  'Red-legged Kittiwake',
  'Red-masked Parakeet',
  'Red-naped Sapsucker',
  'Red-necked Grebe',
  'Red-necked Phalarope',
  'Red-necked Stint',
  'Red-shouldered Hawk',
  'Red-tailed Hawk',
  'Red-tailed Tropicbird',
  'Red-throated Loon',
  'Red-throated Pipit',
  'Red-vented Bulbul',
  'Red-whiskered Bulbul',
  'Red-winged Blackbird',
  'Reddish Egret',
  'Redhead',
  'Rhinoceros Auklet',
  "Ridgway's Rail",
  'Ring-billed Gull',
  'Ring-necked Duck',
  'Ring-necked Pheasant',
  'Ringed Kingfisher',
  "Rivoli's Hummingbird",
  'Rock Pigeon',
  'Rock Ptarmigan',
  'Rock Sandpiper',
  'Rock Wren',
  'Rose-breasted Grosbeak',
  'Rose-ringed Parakeet',
  'Rose-throated Becard',
  'Roseate Spoonbill',
  'Roseate Tern',
  "Ross's Goose",
  "Ross's Gull",
  'Rosy-faced Lovebird',
  'Rough-legged Hawk',
  'Royal Tern',
  'Ruby-crowned Kinglet',
  'Ruby-throated Hummingbird',
  'Ruddy Duck',
  'Ruddy Ground Dove',
  'Ruddy Turnstone',
  'Ruff',
  'Ruffed Grouse',
  'Rufous Hummingbird',
  'Rufous-backed Robin',
  'Rufous-capped Warbler',
  'Rufous-crowned Sparrow',
  'Rufous-winged Sparrow',
  'Rustic Bunting',
  'Rusty Blackbird',
  "Sabine's Gull",
  'Saffron Finch',
  'Sage Thrasher',
  'Sagebrush Sparrow',
  'Saltmarsh Sparrow',
  'Sanderling',
  'Sandhill Crane',
  'Sandwich Tern',
  'Sargasso Shearwater',
  'Savannah Sparrow',
  "Say's Phoebe",
  'Scaled Quail',
  'Scaly-breasted Munia',
  'Scarlet Tanager',
  'Scissor-tailed Flycatcher',
  "Scopoli's Shearwater",
  "Scott's Oriole",
  "Scripps's Murrelet",
  'Seaside Sparrow',
  'Sedge Wren',
  'Semipalmated Plover',
  'Semipalmated Sandpiper',
  'Sharp-shinned Hawk',
  'Sharp-tailed Grouse',
  'Sharp-tailed Sandpiper',
  'Shiny Cowbird',
  'Short-billed Dowitcher',
  'Short-billed Gull',
  'Short-eared Owl',
  'Short-tailed Albatross',
  'Short-tailed Hawk',
  'Short-tailed Shearwater',
  'Siberian Pipit',
  'Siberian Rubythroat',
  'Siberian Sand-Plover',
  'Slaty-backed Gull',
  'Smew',
  "Smith's Longspur",
  'Smooth-billed Ani',
  'Snail Kite',
  'Snow Bunting',
  'Snow Goose',
  'Snowy Egret',
  'Snowy Owl',
  'Snowy Plover',
  'Solitary Sandpiper',
  'Song Sparrow',
  'Sooty Grouse',
  'Sooty Shearwater',
  'Sooty Tern',
  'Sora',
  'South Polar Skua',
  'Spectacled Eider',
  'Spot-breasted Oriole',
  'Spotted Dove',
  'Spotted Owl',
  'Spotted Sandpiper',
  'Spotted Towhee',
  "Sprague's Pipit",
  'Spruce Grouse',
  "Stejneger's Scoter",
  "Steller's Eider",
  "Steller's Jay",
  'Stilt Sandpiper',
  'Sulphur-bellied Flycatcher',
  'Summer Tanager',
  'Surf Scoter',
  'Surfbird',
  "Swainson's Hawk",
  "Swainson's Thrush",
  "Swainson's Warbler",
  'Swallow-tailed Kite',
  'Swamp Sparrow',
  'Taiga Bean-Goose',
  "Temminck's Stint",
  'Tennessee Warbler',
  'Terek Sandpiper',
  'Thick-billed Kingbird',
  'Thick-billed Longspur',
  'Thick-billed Murre',
  "Townsend's Solitaire",
  "Townsend's Storm-Petrel",
  "Townsend's Warbler",
  'Tree Swallow',
  'Tricolored Blackbird',
  'Tricolored Heron',
  'Trindade Petrel',
  "Tristram's Storm-Petrel",
  'Tropical Kingbird',
  'Tropical Parula',
  'Trumpeter Swan',
  'Tufted Duck',
  'Tufted Puffin',
  'Tufted Titmouse',
  'Tundra Bean-Goose',
  'Tundra Swan',
  'Turkey Vulture',
  'Upland Sandpiper',
  'Varied Bunting',
  'Varied Thrush',
  "Vaux's Swift",
  'Veery',
  'Verdin',
  'Vermilion Flycatcher',
  'Vesper Sparrow',
  'Violet-crowned Hummingbird',
  'Violet-green Swallow',
  'Virginia Rail',
  "Virginia's Warbler",
  'Wandering Tattler',
  'Warbling Vireo',
  'Warbling White-eye',
  'Wedge-tailed Shearwater',
  'Western Bluebird',
  'Western Cattle Egret',
  'Western Flycatcher',
  'Western Grebe',
  'Western Gull',
  'Western Kingbird',
  'Western Meadowlark',
  'Western Sandpiper',
  'Western Screech-Owl',
  'Western Spindalis',
  'Western Tanager',
  'Western Wood-Pewee',
  'Whimbrel',
  'Whiskered Auklet',
  'Whiskered Screech-Owl',
  'White Ibis',
  'White Tern',
  'White Wagtail',
  'White-breasted Nuthatch',
  'White-crowned Pigeon',
  'White-crowned Sparrow',
  'White-eared Hummingbird',
  'White-eyed Vireo',
  'White-faced Ibis',
  'White-faced Storm-Petrel',
  'White-headed Woodpecker',
  'White-necked Petrel',
  'White-rumped Sandpiper',
  'White-rumped Shama',
  'White-tailed Hawk',
  'White-tailed Kite',
  'White-tailed Ptarmigan',
  'White-tailed Tropicbird',
  'White-throated Sparrow',
  'White-throated Swift',
  'White-tipped Dove',
  'White-winged Crossbill',
  'White-winged Dove',
  'White-winged Parakeet',
  'White-winged Scoter',
  'Whooper Swan',
  'Whooping Crane',
  'Wild Turkey',
  'Willet',
  "Williamson's Sapsucker",
  'Willow Flycatcher',
  'Willow Ptarmigan',
  "Wilson's Phalarope",
  "Wilson's Plover",
  "Wilson's Snipe",
  "Wilson's Storm-Petrel",
  "Wilson's Warbler",
  'Winter Wren',
  'Wood Duck',
  'Wood Sandpiper',
  'Wood Stork',
  'Wood Thrush',
  "Woodhouse's Scrub-Jay",
  'Worm-eating Warbler',
  'Wrentit',
  'Yellow Rail',
  'Yellow Warbler',
  'Yellow-bellied Flycatcher',
  'Yellow-bellied Sapsucker',
  'Yellow-billed Cardinal',
  'Yellow-billed Cuckoo',
  'Yellow-billed Loon',
  'Yellow-billed Magpie',
  'Yellow-breasted Chat',
  'Yellow-chevroned Parakeet',
  'Yellow-crowned Night Heron',
  'Yellow-eyed Junco',
  'Yellow-faced Grassquit',
  'Yellow-footed Gull',
  'Yellow-fronted Canary',
  'Yellow-green Vireo',
  'Yellow-headed Blackbird',
  'Yellow-rumped Warbler',
  'Yellow-throated Vireo',
  'Yellow-throated Warbler',
  'Zebra Dove',
  'Zone-tailed Hawk',
];

export default birdNames;
